# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Submit a new Beta Build to App Center"
  lane :pushToAppCenter do
    xcversion(version: "10.2")

    # Build
    gym(
      scheme: "YumiMobileAds-Example",
      workspace: "Example/YumiMobileAds.xcworkspace",
      configuration: "Release",
      clean: true,
      include_bitcode: false,
      include_symbols: true,
      export_method: "enterprise",
    )

    # push to App Center
    appcenter_upload(
      api_token: "432d532f9c8d234a64d9ffc626d81ba5f9646dae",
      owner_name: "YumiSDK",
      app_name: "YumiMobileAds-iOS",
      ipa: "./YumiMobileAds_Example.ipa",
      dsym: "./YumiMobileAds_Example.app.dSYM.zip",
      release_notes: "",
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
  )
  end
end
